### PR TITLE
Unhandled AccessViolationException when fixing a broken face

### PR DESCRIPTION
**Pull request by Artoymyp**
Fix for a crash in master branch. that occurs during geometry context creation for the attached file (XbimXplorer is just crashing on file open).
[BrokenFaceTest.stripped.zip](https://github.com/xBimTeam/XbimGeometry/files/1526741/BrokenFaceTest.stripped.zip)

The crash is due to ShapeFix_Face.Context() == NULL when executing ShapeFix_Face.Perform().

PS: I'm not very fluent in OCC, so I don't really understand the fix that I'm proposing, but the file is now opening just OK in master branch.
PSS: I'm sorry, but I have failed to compile develop branch, so I cannot check that the problem is not already fixed in develop branch by some indirect method.

### CODE REVIEW

**Comment by Artoymyp** [comment]
Immediate merge is not so important for me. But I will be extremely grateful if some experienced person would examine my fix and say if it is valid and makes sense from OCC-point-of-view and can be used in production code.

**Comment by CBenghi** [comment]
@Artoymyp,
thanks I'll look into this.

re: develop not compiling you probably just need to add the develop feed to your machine nuget repositories:

If you use Visual Studio 2015+ add the following:
https://www.myget.org/F/xbim-develop/api/v3/index.json
If you use Visual Studio 2013+ add the following:
https://www.myget.org/F/xbim-develop/api/v2

Could you let me know if this fixes the problem for compilation? Otherwise I'll have to take action there too.
Claudio

**Comment by Artoymyp** [comment]
Concerning compilation problems. I am using VS2015 with "https://www.myget.org/F/xbim-develop/api/v2" nuget source. I have also tried out the v3 version, just in case.
The errors are these:
Error		Cannot open source file: 'OCC\src\TopOpeBRepTool\TopOpeBRepTool_closing.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\ShapeProcess\ShapeProcess_StackItemOfDictionaryOfOperator_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\ShapeProcess\ShapeProcess_IteratorOfDictionaryOfOperator_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\ShapeProcess\ShapeProcess_DictionaryOfOperator_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\Dico\Dico_StackItemOfDictionaryOfTransient_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\Dico\Dico_StackItemOfDictionaryOfInteger_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\Dico\Dico_IteratorOfDictionaryOfTransient_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\Dico\Dico_IteratorOfDictionaryOfInteger_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\Dico\Dico_DictionaryOfTransient_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: 'OCC\src\Dico\Dico_DictionaryOfInteger_0.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx		
Error		Cannot open source file: '.\OCC\src\MMgt\MMgt_TShared.cxx': No such file or directory	Xbim.Geometry.Engine.Interop - VS2015	C:\Work\GitHub\MyXbimGeometry\Xbim.Geometry.Engine.Interop\c1xx

**Comment by CBenghi** [comment]
Your files opens correctly in develop.
That will probably have to do with the new version of opencascade that we have implemented.
We are now on 7.2.0 in develop.

**Comment by Artoymyp** [comment]
Well, I am disappointed :) My fix is unnecessary and pull request may be closed. 
Can you give me advice, please. Does my fix make any sense for the master branch? We are locally building a master-branch with some hotfixes. And I would like to include this one in out build, if it is correct.

**Comment by CBenghi** [comment]
:)
My view is that it's not detrimental, the missing context is an empty context anyway, so it does not add information to the algorithm. 
I suppose that occ7.2.0 does that independently, when needed.
I'm spending a bit of time in geometry lately and I'm really tempted to give it a strong refactor... but it's so tweaked that i'm a bi worried to introduce regressions. If you have models that you can contribute for refactoring purposes they are always welcome.
Even just running refactoring tests on your machines.
Best,
Claudio

**Comment by Artoymyp** [comment]
If refactoring will bring us a tidbit more long-term reliability, understandability, and performance, you've got my support. 
We have a very diverse collection of ifc-files. They are pretty much private, but I can run local tests, sure thing. Automated tests are preferred. 
As a result of tests I can commit stripped example-files.
Just drop me a message if the help is needed. I'm intending to use your great lib for a couple of coming years.

**Pull request closed without merging**
