### PR TITLE
Fix for large coordinate system

### PR DESCRIPTION
**Pull request by fomayette**
Still WIP, @andyward suggested I create the pull request early to ease collaboration

### CODE REVIEW

**Comment by CBenghi** [comment]
@andyward @fomayette,

this would break binary compatibility with the format, and also would still provide problems for any visualisation engine that uses float precision (e.g. web viewer).

I have a different approach that keeps positions small and takes advantage of the double in the transform to have models correctly placed and shaped, and does not grow file size.

It's currently working in the maintenance/xbim4.x branch.

I would be able to devote time to adapt that to the xbim5 branch in August.

Any views?

**Comment by andyward** [comment]
See also dependent PR: https://github.com/xBimTeam/XbimEssentials/pull/272

Agreed, we shouldn't break the binary formats (either esent or wexbim) without some seamless backward compatibility.

@CBenghi - sounds like we need to take a look at this. I think @martin1cerny may have already done some similar work to support large offsets from origins in the v5 code.

**Comment by fomayette** [comment]
The problem I envision with bringing geometries close to origin but keep floats is that it's only a partial fix.  Murphy's law suggests we do this and in the following week we'll get a model for 50Km of road or something, and floats will again be insufficient.

**Comment by andyward** [comment]
@martin1cerny is best placed to review this - GIS & WCS is really his area. But I would say that once we're into the domain of 50Km roads, then IFC4x2's `IfcAlignments` come into play, so you'd not be modeling a road as a single _1m x 10m x 50,000m_ _BuildingElementProxy_ etc.

**Comment by bekraft** [comment]
At this scale it becomes a question of coordinate system … By interest, are there any examples known mixing CRS (spherical & metrical)? Is this possible?

**Comment by martin1cerny** [comment]
IFC geometry is always defined in a Cartesian coordinate system. But since IFC4 you can precisely define [relation between this system and any CRS](https://standards.buildingsmart.org/IFC/RELEASE/IFC4/ADD2_TC1/HTML/link/ifccoordinateoperation.htm). You can also use multiple Geometric Representation Contexts with different CRS if needed to defined different parts of geometry in different CRSs.

**Comment by martin1cerny** [comment]
I have just reviewed this pull request and I think it should be all right as it is using versioning of the binary stream. As a justification of the change: `float` can only maintain 6 significant digits so any coordinates beyond 999 999.0 will loose the precision when stored as floats in binary. This is very easy to exceed when working in millimetres in some of the national grids.

**Comment by martin1cerny** [comment]
Replaced by #209

**Pull request closed without merging**
